//! Ed25519 (EdDSA) key parsing and raw signature primitives.
//!
//! SPKI (public) and PKCS#8 (private) PEM parsing goes through
//! `ed25519-dalek`'s `pkcs8`/`pem` support, which matches `jose`'s
//! `importSPKI`/`importPKCS8`: both accept the same ASN.1 SPKI/PKCS#8
//! encodings, so key material generated by either implementation is
//! interchangeable byte-for-byte.
//!
//! Verification uses [`ed25519_dalek::VerifyingKey::verify_strict`], which
//! additionally rejects the small class of non-canonical ("malleable")
//! signatures that a cofactored verifier — the kind behind `jose`/Node's
//! WebCrypto, and the original Ed25519 reference implementation — would
//! accept. This is an intentional, recorded strictness decision: a signature
//! that verifies under `jose` may legitimately fail here, and that is by
//! design (see `strict_verification_rejects_cofactor_malleable_signature`
//! below, and RFC 8032's discussion of the cofactored vs. cofactorless
//! verification equations).
//!
//! @see https://www.rfc-editor.org/rfc/rfc8032 (EdDSA)
//! @see https://docs.rs/ed25519-dalek/latest/ed25519_dalek/struct.VerifyingKey.html#method.verify_strict

use ed25519_dalek::pkcs8::{DecodePrivateKey, DecodePublicKey};
use ed25519_dalek::{Signature, Signer as _, SigningKey, VerifyingKey};

use crate::errors::VaultError;

/// Parse an SPKI PEM Ed25519 public key, matching `jose`'s `importSPKI`.
///
/// Rejects (with [`VaultError::InvalidKeyMaterial`]) a PEM containing a
/// private key *before* attempting any cryptographic parse — a fast,
/// string-level guard mirroring the TypeScript verifier's own check — and
/// separately rejects any PEM that is not a well-formed SPKI EdDSA public key
/// (PKCS#1, a wrong-curve/RSA SPKI, or garbage).
pub fn parse_public_key_pem(pem: &str) -> Result<VerifyingKey, VaultError> {
    if pem.contains("PRIVATE KEY") {
        return Err(VaultError::InvalidKeyMaterial {
            message: "A private key was supplied where an SPKI public key is required.".into(),
        });
    }
    VerifyingKey::from_public_key_pem(pem).map_err(|_| VaultError::InvalidKeyMaterial {
        message: "The supplied public key is not an SPKI PEM EdDSA public key.".into(),
    })
}

/// Parse a PKCS#8 PEM Ed25519 private key, matching `jose`'s `importPKCS8`.
pub fn parse_private_key_pem(pem: &str) -> Result<SigningKey, VaultError> {
    SigningKey::from_pkcs8_pem(pem).map_err(|_| VaultError::InvalidKeyMaterial {
        message: "The supplied private key is not a PKCS#8 PEM EdDSA private key.".into(),
    })
}

/// Produce a raw 64-byte Ed25519 signature over `message`.
#[must_use]
pub fn sign(signing_key: &SigningKey, message: &[u8]) -> Vec<u8> {
    signing_key.sign(message).to_bytes().to_vec()
}

/// Verify a raw Ed25519 signature over `message` against `verifying_key`,
/// using strict (non-cofactored, canonical-only) verification.
///
/// Returns `false` — never an error — for any structurally invalid signature
/// (wrong length) or one that fails strict verification; there is no
/// distinct "malformed signature" error case here, mirroring the TypeScript
/// verifier's fully-boolean outcome for signature verification itself (only
/// *key* parsing failures are typed errors).
#[must_use]
pub fn verify(verifying_key: &VerifyingKey, message: &[u8], signature: &[u8]) -> bool {
    let Ok(sig_bytes) = <[u8; 64]>::try_from(signature) else {
        return false;
    };
    let signature = Signature::from_bytes(&sig_bytes);
    verifying_key.verify_strict(message, &signature).is_ok()
}

/// The stable key identifier used as a JWS `kid`: base64url (unpadded) of the
/// SHA-256 digest of the key's SPKI DER encoding.
#[must_use]
pub fn kid_for_verifying_key(verifying_key: &VerifyingKey) -> String {
    use base64ct::{Base64UrlUnpadded, Encoding};
    use ed25519_dalek::pkcs8::EncodePublicKey;
    use sha2::{Digest, Sha256};

    // `to_public_key_der()` cannot fail for a valid in-memory VerifyingKey —
    // encoding a key we already hold never hits the decode-time failure
    // modes `DecodePublicKey` guards against.
    let der = verifying_key
        .to_public_key_der()
        .expect("encoding an in-memory VerifyingKey to SPKI DER cannot fail");
    let digest = Sha256::digest(der.as_bytes());
    Base64UrlUnpadded::encode_string(&digest)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_PRIVATE_KEY_PEM: &str =
        include_str!("../../tests/fixtures/signing/ed25519-test-key.pkcs8.pem");
    const TEST_PUBLIC_KEY_PEM: &str =
        include_str!("../../tests/fixtures/signing/ed25519-test-key.spki.pem");

    #[test]
    fn parses_valid_spki_public_key() {
        parse_public_key_pem(TEST_PUBLIC_KEY_PEM).expect("valid SPKI PEM must parse");
    }

    #[test]
    fn parses_valid_pkcs8_private_key() {
        parse_private_key_pem(TEST_PRIVATE_KEY_PEM).expect("valid PKCS#8 PEM must parse");
    }

    #[test]
    fn rejects_private_key_supplied_as_public() {
        let err = parse_public_key_pem(TEST_PRIVATE_KEY_PEM).unwrap_err();
        assert!(matches!(err, VaultError::InvalidKeyMaterial { .. }));
    }

    #[test]
    fn rejects_garbage_public_key() {
        let err = parse_public_key_pem("not a pem at all").unwrap_err();
        assert!(matches!(err, VaultError::InvalidKeyMaterial { .. }));
    }

    #[test]
    fn sign_and_verify_round_trip() {
        let signing_key = parse_private_key_pem(TEST_PRIVATE_KEY_PEM).unwrap();
        let verifying_key = parse_public_key_pem(TEST_PUBLIC_KEY_PEM).unwrap();
        let message = b"hello vaultkeeper";
        let signature = sign(&signing_key, message);
        assert!(verify(&verifying_key, message, &signature));
    }

    #[test]
    fn verify_rejects_tampered_message() {
        let signing_key = parse_private_key_pem(TEST_PRIVATE_KEY_PEM).unwrap();
        let verifying_key = parse_public_key_pem(TEST_PUBLIC_KEY_PEM).unwrap();
        let signature = sign(&signing_key, b"original message");
        assert!(!verify(&verifying_key, b"tampered message", &signature));
    }

    #[test]
    fn verify_rejects_wrong_length_signature() {
        let verifying_key = parse_public_key_pem(TEST_PUBLIC_KEY_PEM).unwrap();
        assert!(!verify(&verifying_key, b"message", b"too-short"));
    }

    #[test]
    fn verify_rejects_too_long_signature() {
        let verifying_key = parse_public_key_pem(TEST_PUBLIC_KEY_PEM).unwrap();
        // Symmetric to `verify_rejects_wrong_length_signature` above: a raw
        // Ed25519 signature is exactly 64 bytes, so 65 bytes (one too many)
        // is rejected on length just as 9 bytes (too few) is.
        let too_long_signature = [0u8; 65];
        assert!(!verify(&verifying_key, b"message", &too_long_signature));
    }

    #[test]
    fn verify_rejects_signature_from_a_different_key() {
        // Basic wrong-key authentication negative case: a signature that is
        // valid under one keypair must not verify against a different,
        // unrelated (but otherwise valid) keypair.
        let signing_key = parse_private_key_pem(TEST_PRIVATE_KEY_PEM).unwrap();
        let message = b"hello vaultkeeper";
        let signature = sign(&signing_key, message);

        // A second, distinct valid Ed25519 keypair — deterministically
        // derived from a fixed seed (not the fixture's) so the test needs no
        // OS randomness while still being a genuinely different key.
        let other_signing_key = SigningKey::from_bytes(&[0x42; 32]);
        let other_verifying_key = other_signing_key.verifying_key();

        assert!(!verify(&other_verifying_key, message, &signature));
    }

    fn hex_decode(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex digit pair"))
            .collect()
    }

    /// Recorded decision: [`verify`] uses `verify_strict`, which rejects a
    /// small class of non-canonical ("malleable") Ed25519 signatures that a
    /// *cofactored* verifier — the kind behind `jose`/Node's `node:crypto`
    /// (which `jose` delegates to on Node), and the original Ed25519
    /// reference implementation — accepts. This is intentional, not a bug:
    /// this test documents it with a concrete signature that verifies under
    /// `jose` but is correctly rejected here.
    ///
    /// Vector #46 from the CCTV (Community Cryptography Test Vectors)
    /// `ed25519vectors` corpus: a raw all-zero 32-byte public key (a
    /// low-order point of order 1 — flag `low_order_A`/`low_order_component_A`)
    /// with a signature over the ASCII message `"ed25519vectors"` that a
    /// cofactored verification equation accepts for that key. Empirically
    /// confirmed against this exact input in this repo:
    /// `node:crypto`'s `crypto.verify(null, msg, spkiKey, sig)` (the same
    /// primitive `jose` uses for Ed25519 on Node) returns `true`; dalek's own
    /// loose `VerifyingKey::verify()` also returns `true`; only
    /// `verify_strict()` (what [`verify`] above calls) returns `false`.
    ///
    /// @see https://github.com/C2SP/CCTV/blob/main/ed25519/README.md
    /// @see https://github.com/C2SP/CCTV/blob/main/ed25519/ed25519vectors.json (vector #46)
    /// @see https://www.rfc-editor.org/rfc/rfc8032 (RFC 8032 EdDSA — cofactored vs.
    ///      cofactorless verification equations)
    #[test]
    fn strict_verification_rejects_cofactor_malleable_signature_jose_would_accept() {
        // Raw 32-byte all-zero public key: the identity element, a low-order
        // point (CCTV flags: low_order_A, low_order_component_A).
        let key_bytes: [u8; 32] = hex_decode(&"00".repeat(32)).try_into().unwrap();
        let signature_bytes: [u8; 64] = hex_decode(
            "b62cf890de42c413b11b1411c9f01f1c4d77aa87ef182258d1251f69af2a350605ba9a796274d80437afa36f1236563f2f3b0aa84cecddc3d20914615ba4fe02",
        )
        .try_into()
        .unwrap();
        let message = b"ed25519vectors";

        let verifying_key = VerifyingKey::from_bytes(&key_bytes)
            .expect("an all-zero 32-byte string is a valid (low-order) compressed point");

        // The underlying dalek primitive: loose verify() accepts (matching
        // jose's cofactored behavior confirmed via node:crypto above);
        // verify_strict() rejects.
        use ed25519_dalek::Verifier as _;
        let raw_signature = Signature::from_bytes(&signature_bytes);
        assert!(
            verifying_key.verify(message, &raw_signature).is_ok(),
            "sanity check: loose verify() must accept this known-malleable vector"
        );

        // Our wrapper, which is what the JWS verifier actually calls, must
        // reject it.
        assert!(
            !verify(&verifying_key, message, &signature_bytes),
            "verify_strict()-backed verify() must reject a cofactor-malleable signature"
        );
    }
}
