/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __testAllVaultErrors: () => any;
export const __testHttpFetch: (a: any, b: any) => any;
export const __testJsSecretBackendDelete: (a: any, b: number, c: number) => any;
export const __testJsSecretBackendExists: (a: any, b: number, c: number) => any;
export const __testJsSecretBackendIsAvailable: (a: any) => any;
export const __testJsSecretBackendList: (a: any) => any;
export const __testJsSecretBackendMeta: (a: any) => [number, number, number];
export const __testJsSecretBackendRetrieve: (a: any, b: number, c: number) => any;
export const __testJsSecretBackendStore: (a: any, b: number, c: number, d: number, e: number) => any;
export const __testPromptApproval: (a: any, b: number, c: number, d: number, e: number) => any;
export const __wbg_wasmauthorization_free: (a: number, b: number) => void;
export const __wbg_wasmvaultkeeper_free: (a: number, b: number) => void;
export const allVaultErrorCodes: () => [number, number];
export const createVaultKeeper: (a: any, b: any) => any;
export const init: () => void;
export const wasmauthorization_claims: (a: number) => [number, number, number];
export const wasmauthorization_readSecret: (a: number) => [number, number, number, number];
export const wasmauthorization_response: (a: number) => [number, number, number];
export const wasmauthorization_secretAvailable: (a: number) => number;
export const wasmvaultkeeper_authorize: (a: number, b: number, c: number) => [number, number, number];
export const wasmvaultkeeper_config: (a: number) => [number, number, number];
export const wasmvaultkeeper_delete: (a: number, b: number, c: number) => any;
export const wasmvaultkeeper_doctor: (a: number) => any;
export const wasmvaultkeeper_retrieve: (a: number, b: number, c: number) => any;
export const wasmvaultkeeper_revokeKey: (a: number) => any;
export const wasmvaultkeeper_rotateKey: (a: number) => any;
export const wasmvaultkeeper_setup: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const wasmvaultkeeper_store: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasm_bindgen__closure__destroy__h1722208547e491cb: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8760ba3086f56474: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1d09f6aac4bd3d03: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
