/**
 * Cross-language wire-compatibility tests for the detached-payload Compact
 * JWS contract (issue #237, AC4).
 *
 * There is no CLI or WASM surface for signing yet (deliberately out of scope
 * for #237 — see the issue's non-goals), so genuine cross-verification can't
 * be driven through the compiled binary the way `packages/cli-tests`'
 * conformance suite drives other commands. Instead, both language
 * implementations independently consume the SAME committed fixture —
 * `crates/vaultkeeper-core/tests/fixtures/signing/vectors.json` plus its
 * companion SPKI/PKCS8 PEM keypair — as the shared source of truth:
 *
 * - The Rust core's `cargo test` suite
 *   (`crates/vaultkeeper-core/tests/unit_tests.rs`, `mod signing`) asserts
 *   `create_detached_jws` reproduces every vector byte-for-byte and that
 *   `verify_detached_jws` accepts every vector.
 * - This file asserts the real TypeScript module
 *   (`packages/vaultkeeper/src/access/jws.ts`) does the same: `verifyDetachedJws`
 *   (jose-backed) accepts every vector, and re-signing the same payload with
 *   the same fixture key via `createDetachedJws` reproduces the exact same
 *   compact JWS string (Ed25519/EdDSA is deterministic per RFC 8032, so
 *   equality here is exact, not "close enough").
 *
 * Together these prove the two implementations are wire-compatible without
 * needing a live cross-process call: the vectors were generated BY this same
 * TS module (see the generator's header comment), so Rust reproducing them
 * byte-for-byte is equivalent to "Rust signs, jose verifies," and this file
 * verifying them again is equivalent to "jose signs, [committed] jose
 * verifies" — the missing "Rust signs, jose verifies" leg collapses to a
 * byte-equality argument once both sides agree on the same bytes.
 *
 * @see https://www.rfc-editor.org/rfc/rfc7515#section-7.2.2 (RFC 7515 §7.2.2 detached-payload Compact JWS)
 * @see https://www.rfc-editor.org/rfc/rfc7797 (RFC 7797 `b64:false` unencoded payload option)
 * @see https://www.rfc-editor.org/rfc/rfc8032 (RFC 8032 EdDSA — deterministic signatures)
 * @see ../../../../../crates/vaultkeeper-core/tests/fixtures/signing/generate-vectors.mts
 */
import * as crypto from 'node:crypto'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import { createDetachedJws, verifyDetachedJws } from '../../../src/access/jws.js'

interface GoldenVector {
  name: string
  kid: string
  payloadBase64: string
  jws: string
}

function isGoldenVector(value: unknown): value is GoldenVector {
  return (
    value !== null &&
    typeof value === 'object' &&
    'name' in value &&
    typeof value.name === 'string' &&
    'kid' in value &&
    typeof value.kid === 'string' &&
    'payloadBase64' in value &&
    typeof value.payloadBase64 === 'string' &&
    'jws' in value &&
    typeof value.jws === 'string'
  )
}

function readGoldenVectors(path: string): GoldenVector[] {
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'))
  if (
    parsed === null ||
    typeof parsed !== 'object' ||
    !('vectors' in parsed) ||
    !Array.isArray(parsed.vectors) ||
    !parsed.vectors.every(isGoldenVector)
  ) {
    throw new Error(`${path} does not match the expected golden-vector shape`)
  }
  return parsed.vectors
}

const here = dirname(fileURLToPath(import.meta.url))
const fixturesDir = join(here, '../../../../../crates/vaultkeeper-core/tests/fixtures/signing')

const publicKeyPem = readFileSync(join(fixturesDir, 'ed25519-test-key.spki.pem'), 'utf8')
const privateKeyPem = readFileSync(join(fixturesDir, 'ed25519-test-key.pkcs8.pem'), 'utf8')
const vectors = readGoldenVectors(join(fixturesDir, 'vectors.json'))

describe('detached-JWS golden vectors (shared with the Rust core)', () => {
  it('has at least the four documented payload shapes', () => {
    const names = vectors.map((v) => v.name).sort()
    expect(names).toEqual(['ascii', 'binary', 'empty', 'utf8-multibyte'].sort())
  })

  it('every vector carries the real derived kid, not an arbitrary label', () => {
    // Regression for a review finding on #237: `kid` must be
    // base64url(sha256(spkiDer)) — the same derivation as `computeKid` in
    // packages/vaultkeeper/src/backend/file-backend.ts — not a hand-picked
    // string. An arbitrary kid would let the vectors pass even if the wrong
    // kid were embedded for a given key.
    const spkiDer = crypto.createPublicKey(publicKeyPem).export({ type: 'spki', format: 'der' })
    const expectedKid = crypto.createHash('sha256').update(spkiDer).digest('base64url')
    for (const vector of vectors) {
      expect(vector.kid).toBe(expectedKid)
    }
  })

  it.each(vectors.map((v) => [v.name, v] as const))(
    'verifyDetachedJws accepts the "%s" vector',
    async (_name, vector) => {
      const payload = Buffer.from(vector.payloadBase64, 'base64')
      const verified = await verifyDetachedJws({ payload, jws: vector.jws, publicKey: publicKeyPem })
      expect(verified).toBe(true)
    },
  )

  it.each(vectors.map((v) => [v.name, v] as const))(
    're-signing the "%s" vector with the fixture key reproduces it byte-for-byte',
    async (_name, vector) => {
      const payload = Buffer.from(vector.payloadBase64, 'base64')
      const jws = await createDetachedJws(vector.kid, payload, (data) =>
        Promise.resolve(crypto.sign(null, data, privateKeyPem)),
      )
      expect(jws).toBe(vector.jws)
    },
  )

  it('rejects a golden vector whose payload has been tampered with', async () => {
    const vector = vectors.find((v) => v.name === 'ascii')
    if (!vector) throw new Error('ascii vector must exist')
    const verified = await verifyDetachedJws({
      payload: Buffer.from('a completely different payload'),
      jws: vector.jws,
      publicKey: publicKeyPem,
    })
    expect(verified).toBe(false)
  })
})
