/**
 * StubTool axis conformance runner (issue #313 AC3 + AC4).
 *
 * Loads the world-mutation / state-conditional-response / shape-assertion
 * corpus exported from `vaultkeeper-conformance`
 * (`stub-scenarios.json`, generated by `cargo run -p vaultkeeper-conformance
 * --bin export-stub-scenarios`) and drives each scenario's steps against the
 * REAL compiled `vk-stub-*` binary — resolved from a test-scoped `PATH` under
 * its real-tool-name symlink (`secret-tool`, `op`), exactly as a real
 * subprocess-driven backend would resolve it — rather than reimplementing
 * the `StubTool` matching engine in TypeScript.
 *
 * This is the JS half of AC3 ("the same fake binary is resolved from a
 * test-scoped PATH by the packages/cli-tests runner"): the Rust half
 * (`crates/vaultkeeper-stub-tools/tests/conformance_axes.rs`) drives the
 * identical corpus in-process through the Rust `StubTool` engine directly.
 * Both assert against the same `expectedExitCode`/`expectedStdout`/
 * `expectedStderr` fields on the same JSON cases, so a divergence between
 * the real subprocess binary's behavior and the in-process engine's
 * behavior shows up as one of these two suites failing while the other
 * passes.
 *
 * @see crates/vaultkeeper-stub-tools/src/tables.rs — the behavior tables
 *   these cases are written against
 * @see crates/vaultkeeper-conformance/src/lib.rs — `stub_scenario_cases()`
 */

import { execFile } from 'node:child_process'
import * as fsSync from 'node:fs'
import * as fs from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it, expect } from 'vitest'
import { matchesOutput, type OutputMatcher } from './matches-output.js'

// ─── Types mirroring the Rust StubScenario / StubStep / OutputMatcher ────

interface StubStep {
  note: string | null
  args: string[]
  stdin: string | null
  expectedExitCode: number
  expectedStdout: OutputMatcher
  expectedStderr: OutputMatcher
}

interface StubScenario {
  tool: string
  steps: StubStep[]
}

interface ConformanceCase {
  name: string
  stubScenario: StubScenario | null
}

// ─── Load cases ──────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const casesPath = path.join(__dirname, 'stub-scenarios.json')
// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment -- JSON.parse returns any; validated by the conformance crate
const cases: ConformanceCase[] = JSON.parse(await fs.readFile(casesPath, 'utf8'))

// ─── Find the compiled vk-stub-* binaries ────────────────────────

function findStubBinary(tool: string): string | null {
  const root = path.resolve(__dirname, '..', '..', '..', '..')
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidate = path.join(root, 'target', 'debug', `vk-stub-${tool}${ext}`)
  try {
    fsSync.accessSync(candidate)
    return candidate
  } catch {
    return null
  }
}

const TOOLS_USED = [...new Set(cases.flatMap((c) => (c.stubScenario ? [c.stubScenario.tool] : [])))]
const BINARIES = new Map(
  TOOLS_USED.map((tool): [string, string | null] => [tool, findStubBinary(tool)]),
)
const ALL_BINARIES_PRESENT =
  TOOLS_USED.length > 0 && TOOLS_USED.every((t) => BINARIES.get(t) !== null)

// ─── Run one scenario ─────────────────────────────────────────────
//
// Issue #313 guardrail 2: the compiled binary is named `vk-stub-<tool>`; a
// symlink named after the *real* tool name (`secret-tool`, `op`, ...) is
// created only inside this test's own scoped PATH directory, and every
// invocation below resolves the tool by its bare real name through that
// PATH — mirroring exactly how a real subprocess-driven backend (via
// `HostPlatform::exec`) would resolve it. Nothing here ever invokes
// `vk-stub-<tool>` by its own binary name.

async function runStep(
  pathDir: string,
  tool: string,
  worldPath: string,
  step: StubStep,
): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  return new Promise((resolve) => {
    const child = execFile(
      tool,
      step.args,
      {
        timeout: 15_000,
        env: {
          ...process.env,
          PATH: `${pathDir}${path.delimiter}${process.env.PATH ?? ''}`,
          VAULTKEEPER_STUB_TOOLS_SENTINEL: '1',
          VAULTKEEPER_STUB_TOOLS_WORLD_PATH: worldPath,
        },
      },
      (error, stdout, stderr) => {
        let exitCode = 0
        if (error !== null) {
          exitCode = typeof error.code === 'number' ? error.code : 1
        }
        resolve({ stdout, stderr, exitCode })
      },
    )

    if (child.stdin !== null) {
      // eslint-disable-next-line @typescript-eslint/no-empty-function -- suppress EPIPE from child exiting before stdin write completes
      child.stdin.on('error', () => {})
      if (step.stdin !== null) {
        child.stdin.write(step.stdin)
      }
      child.stdin.end()
    }
  })
}

function isErrnoException(err: unknown): err is NodeJS.ErrnoException {
  return err instanceof Error && 'code' in err
}

/**
 * Places the compiled `vk-stub-*` binary at `<destDir>/<tool>[.exe]` under
 * its real-tool-name — a symlink where possible, falling back to a copy on
 * Windows when symlink creation is denied (a non-elevated process without
 * Developer Mode enabled gets `EPERM`/`EACCES` from `fs.symlink`, per
 * Node's documented Windows symlink permission requirements).
 */
async function linkStubBinary(binary: string, destDir: string, tool: string): Promise<void> {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const dest = path.join(destDir, `${tool}${ext}`)
  try {
    await fs.symlink(binary, dest)
  } catch (err) {
    const isWindowsPermissionDenial =
      process.platform === 'win32' &&
      isErrnoException(err) &&
      (err.code === 'EPERM' || err.code === 'EACCES')
    if (!isWindowsPermissionDenial) throw err
    await fs.copyFile(binary, dest)
    await fs.chmod(dest, 0o755)
  }
}

// ─── Test suite ──────────────────────────────────────────────────

// Skipped when the vk-stub-* binaries this corpus needs aren't built yet
// (e.g. a TS-only CI job) — mirrors run-conformance.test.ts's
// RUST_BIN-not-found skip.
describe.skipIf(!ALL_BINARIES_PRESENT)(
  'StubTool axis conformance (real vk-stub-* subprocess)',
  () => {
    const scenarioCases = cases.filter(
      (c): c is ConformanceCase & { stubScenario: StubScenario } => c.stubScenario !== null,
    )

    it.each(
      scenarioCases.map((c): [string, ConformanceCase & { stubScenario: StubScenario }] => [
        c.name,
        c,
      ]),
    )('%s', async (_name, testCase) => {
      const tool = testCase.stubScenario.tool
      const binary = BINARIES.get(tool)
      if (binary === null || binary === undefined) {
        throw new Error(`no vk-stub-${tool} binary resolved`)
      }

      const pathDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vk-stub-path-'))
      const worldDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vk-stub-world-'))
      const worldPath = path.join(worldDir, 'world.json')

      try {
        await linkStubBinary(binary, pathDir, tool)

        for (const [i, step] of testCase.stubScenario.steps.entries()) {
          const result = await runStep(pathDir, tool, worldPath, step)
          const errors: string[] = []

          if (result.exitCode !== step.expectedExitCode) {
            errors.push(
              `exit code: expected ${String(step.expectedExitCode)}, got ${String(result.exitCode)}`,
            )
          }
          if (!matchesOutput(step.expectedStdout, result.stdout)) {
            errors.push(
              `stdout mismatch: expected ${JSON.stringify(step.expectedStdout)}, got ${JSON.stringify(result.stdout)}`,
            )
          }
          if (!matchesOutput(step.expectedStderr, result.stderr)) {
            errors.push(
              `stderr mismatch: expected ${JSON.stringify(step.expectedStderr)}, got ${JSON.stringify(result.stderr)}`,
            )
          }

          if (errors.length > 0) {
            expect.fail(
              `step ${String(i)} (${step.note ?? 'no note'}, argv ${JSON.stringify(step.args)}):\n  ${errors.join('\n  ')}`,
            )
          }
        }
      } finally {
        await fs.rm(worldDir, { recursive: true, force: true })
        await fs.rm(pathDir, { recursive: true, force: true })
      }
    })
  },
)

// Guards against the corpus silently going empty (a `describe.skipIf` with
// zero `it.each` cases reports as passing, which would hide the exact
// regression this suite exists to catch).
describe('stub-scenarios.json sanity', () => {
  it('has at least one case per StubTool axis represented', () => {
    expect(cases.filter((c) => c.stubScenario !== null).length).toBeGreaterThanOrEqual(3)
  })
})
